name: Test twistlock cli in GitHub Actions

on:
  push:
    branches: [master]

jobs:
  docker-image-scanning:

    runs-on: ubuntu-latest

    steps:
    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2
    
    - name: Print ip
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t localbuild/goodimage .
        
    - name: download twistlock
      run: |
        curl --progress-bar -L -k --header "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia29kYWkuaGlyYWlzaGlAcGxhbnZpZXcuY29tIiwicm9sZSI6ImFkbWluIiwiZ3JvdXBzIjpudWxsLCJyb2xlUGVybXMiOltbMjU1LDI1NSwyNTUsMjU1LDI1NSwxMjcsMV0sWzI1NSwyNTUsMjU1LDI1NSwyNTUsMTI3LDFdXSwic2Vzc2lvblRpbWVvdXRTZWMiOjE4MDAsImV4cCI6MTY2ODAzMzUyOSwiaXNzIjoidHdpc3Rsb2NrIn0.NJAyUiERfeEE5D9881OaewjRQdupXbKcxgZm-9Jv_-c" https://ec2-44-193-79-201.compute-1.amazonaws.com:8083/api/v1/util/twistcli > twistcli; chmod a+x twistcli;
    
    - name: check twistlock version
      run: |
        ./twistcli --version
        
    - name: scan docker image
      run: |
        ./twistcli images scan localbuild/goodimage --address https://ec2-44-193-79-201.compute-1.amazonaws.com:8083/ -u ${{ secrets.TWISTLOCK_USERNAME }} -p ${{ TWISTLOCK_PASSWORD }}
    
