name: Test twistlock cli in GitHub Actions

on:
  push:
    branches: [main]

jobs:
  docker-image-scanning:

    runs-on: ubuntu-latest

    steps:
    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2
    
    - name: Print ip
      run: |
        echo ${{ steps.ip.ipv4 }}
